import { Link } from "react-router-dom";
import { ArrowRight, CalendarCheck2, Search, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

const Home=()=> <section style={{width:"100%"}}>
  <div className="home-hero">
    <div><div className="page-eyebrow"><Sparkles size={13} style={{verticalAlign:"middle",marginRight:5}}/> Learn. Teach. Connect.</div><h1 style={{fontSize:"clamp(42px,6vw,68px)",lineHeight:1.02,letterSpacing:"-.055em",fontWeight:900,color:"#172033",margin:"14px 0 18px"}}>Turn knowledge into <span style={{color:"#5b5ce2"}}>real progress.</span></h1><p style={{fontSize:16,lineHeight:1.75,color:"#667085",maxWidth:560}}>SkillSync makes one-to-one learning simple. Discover practical skills, find the right mentor, book an available time and keep every session organized.</p><div style={{display:"flex",gap:10,marginTop:25,flexWrap:"wrap"}}><Link to="/skills" className="btn-primary">Explore skills <ArrowRight size={16}/></Link><Link to="/register" className="btn-secondary">Create free account</Link></div><div style={{display:"flex",gap:22,marginTop:28,flexWrap:"wrap"}}><span className="result-count"><ShieldCheck size={15} style={{verticalAlign:"middle",marginRight:5}}/> Secure access</span><span className="result-count"><CalendarCheck2 size={15} style={{verticalAlign:"middle",marginRight:5}}/> Flexible booking</span><span className="result-count"><UsersRound size={15} style={{verticalAlign:"middle",marginRight:5}}/> Mentor-led</span></div></div>
    <div className="surface" style={{padding:16,background:"linear-gradient(145deg,#eef0ff,#fff)"}}><div style={{borderRadius:14,background:"#fff",padding:20,boxShadow:"0 18px 50px rgba(58,63,130,.12)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div className="page-eyebrow">Your learning hub</div><h2 style={{margin:"5px 0 0",fontSize:23,fontWeight:850,color:"#172033"}}>Find your next skill</h2></div><div className="brand-mark"><Search size={18}/></div></div><div style={{marginTop:20,display:"grid",gap:10}}>{["React & Frontend","System Design","Python & APIs"].map((x,i)=><div key={x} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:14,border:"1px solid #e9ebf2",borderRadius:12}}><div><strong style={{fontSize:13,color:"#344054"}}>{x}</strong><div className="result-count" style={{marginTop:3}}>{["Intermediate","Advanced","Beginner"][i]} · Mentor session</div></div><ArrowRight size={16} color="#6668d8"/></div>)}</div><div style={{marginTop:15,padding:13,borderRadius:11,background:"#f7f8ff",color:"#6668d8",fontSize:12,fontWeight:700}}>Search, filter by level and availability, then book your preferred slot.</div></div></div>
  </div>
  <div className="home-features">{[[Search,"Discover","Find skills with search, filters and sorting."],[CalendarCheck2,"Book with confidence","Choose an open slot that fits your schedule."],[UsersRound,"Share what you know","Publish your own skills and mentor others."]].map(([Icon,title,text])=><div className="surface" style={{padding:22}} key={title}><div className="empty-icon" style={{margin:0}}><Icon size={20}/></div><h3 style={{margin:"15px 0 6px",fontSize:16,fontWeight:800,color:"#172033"}}>{title}</h3><p style={{color:"#7b8495",fontSize:13,lineHeight:1.65}}>{text}</p></div>)}</div>
</section>;
export default Home;
