import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { getMyBookings, confirmBooking, completeBooking, cancelBooking } from "../api/booking.js";
import { useAuth } from "../context/authContext.jsx";
import { CalendarCheck2, Check, X, CircleCheck } from "lucide-react";

const MyBookings=()=>{ const {user}=useAuth(); const qc=useQueryClient(); const [workingId,setWorkingId]=useState(null); const [actionError,setActionError]=useState(""); const {data:bookings=[],isLoading,error}=useQuery({queryKey:["my-bookings"],queryFn:getMyBookings});
 const runAction=async(id,action)=>{setWorkingId(id);setActionError("");try{await action(id);await qc.invalidateQueries({queryKey:["my-bookings"]});await qc.invalidateQueries({queryKey:["my-slots"]});await qc.invalidateQueries({queryKey:["dashboard"]});}catch(e){setActionError(e.response?.data?.error||"Action failed.")}finally{setWorkingId(null)}};
 if(isLoading)return <div className="empty-state"><div className="empty-icon"><CalendarCheck2 size={20}/></div><h2>Loading bookings</h2></div>; if(error)return <div className="form-error">Could not load bookings.</div>;
 return <section><div className="page-header"><div><div className="page-eyebrow">Bookings</div><h1 className="page-title">My bookings</h1><p className="page-subtitle">Manage every learning and teaching session in one place.</p></div></div>{actionError&&<div className="form-error" style={{marginBottom:16}}>{actionError}</div>}{bookings.length===0?<div className="empty-state"><div className="empty-icon"><CalendarCheck2 size={21}/></div><h2>No bookings yet</h2><p>Book a skill session from Explore to see it here.</p></div>:<div className="list-stack">{bookings.map(b=>{const isAdmin=String(b.admin?._id)===String(user._id);const isUser=String(b.user?._id)===String(user._id);const working=workingId===b._id;const canCancel=["pending","confirmed"].includes(b.status);return <article key={b._id} className="surface" style={{padding:18}}><div className="booking-row" style={{padding:0,border:0,boxShadow:"none"}}><div className="booking-main"><div className="booking-title">{b.skill?.name||"Skill"}</div><div className="booking-meta"><span>📅 {new Date(b.slot?.start||b.scheduledFor).toLocaleString()}</span><span>{isAdmin?"Student: ":"Mentor: "}{isUser?b.admin?.name:b.user?.name}</span></div></div><span className={`status ${b.status}`}>{b.status}</span></div><div style={{display:"flex",gap:8,marginTop:15,flexWrap:"wrap"}}>{isAdmin&&b.status==="pending"&&<button className="btn-success" disabled={working} onClick={()=>runAction(b._id,confirmBooking)}><Check size={14}/> Confirm</button>}{isAdmin&&b.status==="confirmed"&&<button className="btn-primary" disabled={working} onClick={()=>runAction(b._id,completeBooking)}><CircleCheck size={14}/> Complete</button>}{(isAdmin||isUser)&&canCancel&&<button className="btn-danger" disabled={working} onClick={()=>runAction(b._id,cancelBooking)}><X size={14}/> Cancel</button>}</div></article>})}</div>}</section>;
}; export default MyBookings;
