import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { fetchSkills } from "../api/skills.js";
import { createSlot,deleteSlot,getMySlots } from "../api/slot.js";
import { useAuth } from "../context/authContext.jsx";
import { Clock3, Plus, Trash2 } from "lucide-react";

const MySlots=()=>{const{user}=useAuth();const qc=useQueryClient();const[form,setForm]=useState({skill:"",start:"",end:""});const{data:result}=useQuery({queryKey:["owned-skill-options"],queryFn:()=>fetchSkills({limit:100})});const skills=result?.data??[];const{data:slots=[],isLoading}=useQuery({queryKey:["my-slots"],queryFn:getMySlots});const owned=skills.filter(s=>String(s.owner?._id||s.owner)===String(user._id));const add=useMutation({mutationFn:createSlot,onSuccess:()=>{qc.invalidateQueries({queryKey:["my-slots"]});qc.invalidateQueries({queryKey:["dashboard"]});setForm({skill:"",start:"",end:""})}});const remove=useMutation({mutationFn:deleteSlot,onSuccess:()=>qc.invalidateQueries({queryKey:["my-slots"]})});const submit=e=>{e.preventDefault();add.mutate({skill:form.skill,start:new Date(form.start).toISOString(),end:new Date(form.end).toISOString()})};return <section><div className="page-header"><div><div className="page-eyebrow">Teaching</div><h1 className="page-title">My teaching slots</h1><p className="page-subtitle">Publish availability so learners can book a session with you.</p></div></div>{owned.length===0?<div className="empty-state"><div className="empty-icon"><Plus size={20}/></div><h2>Create a skill first</h2><p>Add a skill from Explore before publishing a slot.</p></div>:<form onSubmit={submit} className="surface form-card"><div className="section-row"><div><h2 className="section-title">Publish availability</h2><p className="page-subtitle">Choose the skill and define a start and end time.</p></div></div><div className="form-grid"><div><label className="field-label">Skill</label><select required className="field" value={form.skill} onChange={e=>setForm({...form,skill:e.target.value})}><option value="">Choose a skill</option>{owned.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select></div><div></div><div><label className="field-label">Start</label><input required className="field" type="datetime-local" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></div><div><label className="field-label">End</label><input required className="field" type="datetime-local" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></div></div>{add.isError&&<div className="form-error" style={{marginTop:14}}>{add.error.response?.data?.error||"Could not create slot."}</div>}<div className="form-footer"><button className="btn-primary" disabled={add.isPending}><Plus size={15}/>{add.isPending?"Publishing...":"Publish slot"}</button></div></form>}
 <div className="dashboard-section"><div className="section-row"><div><h2 className="section-title">Published slots</h2><p className="page-subtitle">Manage your upcoming availability.</p></div></div>{isLoading?<div className="empty-state">Loading slots...</div>:slots.length===0?<div className="empty-state"><div className="empty-icon"><Clock3 size={20}/></div><h2>No slots published</h2><p>Your available times will appear here.</p></div>:<div className="list-stack">{slots.map(slot=><div key={slot._id} className="booking-row"><div className="booking-main"><div className="booking-title">{slot.skill?.name||"Skill"}</div><div className="booking-meta"><span>📅 {new Date(slot.start).toLocaleString()}</span><span>Until {new Date(slot.end).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div></div><div style={{display:"flex",alignItems:"center",gap:10}}><span className={`status ${slot.isBooked?"confirmed":"completed"}`}>{slot.isBooked?"Booked":"Open"}</span>{!slot.isBooked&&<button className="btn-danger" onClick={()=>remove.mutate(slot._id)}><Trash2 size={14}/></button>}</div></div>)}</div>}</div></section>};export default MySlots;
